/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  endpointpolicymanagerSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Overview',
    },

    // Getting Started
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [
        'getting-started/index',
        'getting-started/basic-concepts',
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
      collapsed: false,
    },

    // Installation and Deployment
    {
      type: 'category',
      label: '⚙️ Installation and Deployment',
      items: [
        {
          type: 'autogenerated',
          dirName: 'installation-and-deployment',
        },
      ],
    },

    // Licensing
    {
      type: 'category',
      label: '📜 Licensing',
      items: [
        'licensing/index',
        {
          type: 'autogenerated',
          dirName: 'licensing',
        },
      ],
    },

    // Policy Management
    {
      type: 'category',
      label: '📋 Policy Management',
      items: [
        {
          type: 'category',
          label: 'Administrative Templates',
          items: [
            {
              type: 'autogenerated',
              dirName: 'policy-management/administrative-templates',
            },
          ],
        },
        {
          type: 'category',
          label: 'Preferences',
          items: [
            {
              type: 'autogenerated',
              dirName: 'policy-management/preferences',
            },
          ],
        },
        {
          type: 'category',
          label: 'Item Level Targeting',
          items: [
            {
              type: 'autogenerated',
              dirName: 'policy-management/item-level-targeting',
            },
          ],
        },
      ],
    },

    // Application Management
    {
      type: 'category',
      label: '🖥️ Application Management',
      items: [
        {
          type: 'category',
          label: 'Application Settings',
          items: [
            {
              type: 'autogenerated',
              dirName: 'application-management/application-settings',
            },
          ],
        },
        {
          type: 'category',
          label: 'File Associations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'application-management/file-associations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Java Enterprise Rules',
          items: [
            {
              type: 'autogenerated',
              dirName: 'application-management/java-enterprise-rules',
            },
          ],
        },
        {
          type: 'category',
          label: 'Browser Router',
          items: [
            {
              type: 'autogenerated',
              dirName: 'application-management/browser-router',
            },
          ],
        },
      ],
    },

    // Security and Privilege Management
    {
      type: 'category',
      label: '🔒 Security and Privilege Management',
      items: [
        {
          type: 'category',
          label: 'Least Privilege Manager',
          items: [
            {
              type: 'autogenerated',
              dirName: 'security-and-privilege-management/least-privilege-manager',
            },
          ],
        },
        {
          type: 'category',
          label: 'Security Settings',
          items: [
            {
              type: 'autogenerated',
              dirName: 'security-and-privilege-management/security-settings',
            },
          ],
        },
        {
          type: 'category',
          label: 'GPO Export',
          items: [
            {
              type: 'autogenerated',
              dirName: 'security-and-privilege-management/gpo-export',
            },
          ],
        },
      ],
    },

    // Device and Desktop Management
    {
      type: 'category',
      label: '🖱️ Device and Desktop Management',
      items: [
        {
          type: 'category',
          label: 'Device Manager',
          items: [
            {
              type: 'autogenerated',
              dirName: 'device-and-desktop-management/device-manager',
            },
          ],
        },
        {
          type: 'category',
          label: 'Start Screen and Taskbar',
          items: [
            {
              type: 'autogenerated',
              dirName: 'device-and-desktop-management/start-screen-and-taskbar',
            },
          ],
        },
        {
          type: 'category',
          label: 'Remote Desktop Protocol',
          items: [
            {
              type: 'autogenerated',
              dirName: 'device-and-desktop-management/remote-desktop-protocol',
            },
          ],
        },
      ],
    },

    // Cloud and Remote Management
    {
      type: 'category',
      label: '☁️ Cloud and Remote Management',
      items: [
        {
          type: 'category',
          label: 'Cloud Management',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-and-remote-management/cloud-management',
            },
          ],
        },
        {
          type: 'category',
          label: 'Remote Work Delivery',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-and-remote-management/remote-work-delivery',
            },
          ],
        },
        {
          type: 'category',
          label: 'MDM Integration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-and-remote-management/mdm-integration',
            },
          ],
        },
      ],
    },

    // Automation and Scripting
    {
      type: 'category',
      label: '🤖 Automation and Scripting',
      items: [
        {
          type: 'category',
          label: 'Scripts and Triggers',
          items: [
            {
              type: 'autogenerated',
              dirName: 'automation-and-scripting/scripts-and-triggers',
            },
          ],
        },
        {
          type: 'category',
          label: 'Feature Management',
          items: [
            {
              type: 'autogenerated',
              dirName: 'automation-and-scripting/feature-management',
            },
          ],
        },
      ],
    },

    // Compliance and Reporting
    {
      type: 'category',
      label: '📊 Compliance and Reporting',
      items: [
        {
          type: 'category',
          label: 'Group Policy Compliance Reporter',
          items: [
            {
              type: 'autogenerated',
              dirName: 'compliance-and-reporting/group-policy-compliance-reporter',
            },
          ],
        },
        {
          type: 'category',
          label: 'Editions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'compliance-and-reporting/editions',
            },
          ],
        },
      ],
    },

    // Deployment Methods
    {
      type: 'category',
      label: '🚢 Deployment Methods',
      items: [
        {
          type: 'category',
          label: 'Group Policy',
          items: [
            {
              type: 'autogenerated',
              dirName: 'deployment-methods/group-policy',
            },
          ],
        },
        {
          type: 'category',
          label: 'Software Packages',
          items: [
            {
              type: 'autogenerated',
              dirName: 'deployment-methods/software-packages',
            },
          ],
        },
      ],
    },

    // Integrations
    {
      type: 'category',
      label: '🔗 Integrations',
      items: [
        {
          type: 'category',
          label: 'Third-Party Integrations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'integrations/third-party-integrations',
            },
          ],
        },
      ],
    },

    // Platform Specific
    {
      type: 'category',
      label: '💻 Platform Specific',
      items: [
        {
          type: 'category',
          label: 'Mac Support',
          items: [
            {
              type: 'autogenerated',
              dirName: 'platform-specific/mac-support',
            },
          ],
        },
        {
          type: 'category',
          label: 'Windows Requirements',
          items: [
            {
              type: 'autogenerated',
              dirName: 'platform-specific/windows-requirements',
            },
          ],
        },
      ],
    },

    // Resources
    {
      type: 'category',
      label: '📚 Resources',
      items: ['resources/knowledge-base', 'resources/video-tutorials'],
    },

    // Troubleshooting
    {
      type: 'category',
      label: '🔧 Troubleshooting',
      items: [
        'troubleshooting/index',
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
    },

    // Reference
    {
      type: 'category',
      label: '📖 Reference',
      items: ['reference/index'],
    },

    // Archive
    {
      type: 'category',
      label: '📦 Archive',
      items: [
        {
          type: 'category',
          label: 'Archived Guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'archive/archived-guides',
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
