// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Main sidebar showing all products
  productSidebar: [
    {
      type: 'category',
      label: '1Secure',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '1Secure',
        },
      ],
    },
    // Add more products here as they are added to the docs folder
    // Example:
    // {
    //   type: 'category',
    //   label: 'ProductName',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'ProductName',
    //     },
    //   ],
    // },
  ],
};

export default sidebars;
