// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  identityManagerSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'IdentityManager SaaS Overview',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: ['getting-started/index', 'getting-started/requirements', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: ['architecture/index', 'architecture/saas', 'architecture/on-premise', 'architecture/secure-agent-communication'],
    },
    {
      type: 'category',
      label: 'Installation',
      collapsed: true,
      items: [
        'installation/index',
        'installation/overview',
        {
          type: 'category',
          label: 'Production Setup',
          collapsed: true,
          items: [
            'installation/production-setup/index',
            'installation/production-setup/database',
            'installation/production-setup/server',
            'installation/production-setup/agent',
            'installation/production-setup/email-server',
            'installation/production-setup/working-directory',
          ],
        },
        'installation/reverse-proxy',
      ],
    },
    {
      type: 'category',
      label: 'Identity Management',
      collapsed: true,
      items: [
        'identity-management/index',
        'identity-management/identity-repository',
        'identity-management/entity-model',
        {
          type: 'category',
          label: 'Joiners, Movers & Leavers',
          collapsed: true,
          items: [
            'identity-management/joiners-movers-leavers/index',
            'identity-management/joiners-movers-leavers/onboarding-offboarding',
            'identity-management/joiners-movers-leavers/position-changes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Access Control',
      collapsed: true,
      items: [
        'access-control/resources',
        {
          type: 'category',
          label: 'Profiles & Permissions',
          collapsed: true,
          items: [
            'access-control/profiles-and-permissions/index',
            'access-control/profiles-and-permissions/create-assign-profiles',
            'access-control/profiles-and-permissions/permissions',
            'access-control/profiles-and-permissions/rights-restriction',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Role Management',
      collapsed: true,
      items: [
        'role-management/index',
        'role-management/role-model',
        'role-management/role-model-rules',
        'role-management/role-mining',
        'role-management/simulation',
        {
          type: 'category',
          label: 'Role Assignment',
          collapsed: true,
          items: [
            'role-management/role-assignment/index',
            'role-management/role-assignment/assignment-dates',
            'role-management/role-assignment/existing-assignments',
            'role-management/role-assignment/entitlement-assignments',
            'role-management/role-assignment/conforming-assignments',
            'role-management/role-assignment/nonconforming-detection',
            'role-management/role-assignment/evaluate-policy',
            'role-management/role-assignment/generate-contexts',
            'role-management/role-assignment/infer-single-roles',
            'role-management/role-assignment/indirect-permissions',
            'role-management/role-assignment/configure-indirect-permissions',
            'role-management/role-assignment/restrict-assignments',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Connectors',
      collapsed: true,
      items: [
        'connectors/index',
        {
          type: 'category',
          label: 'Configuration',
          collapsed: true,
          items: [
            'connectors/configuration/index',
            'connectors/configuration/connections',
            'connectors/configuration/entity-property-mapping',
            'connectors/configuration/credential-protection',
            'connectors/configuration/secured-options',
          ],
        },
        {
          type: 'category',
          label: 'Connector Reference',
          collapsed: true,
          items: [
            'connectors/connector-reference/index',
            'connectors/connector-reference/active-directory',
            'connectors/connector-reference/azure',
            'connectors/connector-reference/csv',
            'connectors/connector-reference/easyvista',
            'connectors/connector-reference/easyvista-ticket',
            'connectors/connector-reference/excel',
            'connectors/connector-reference/google-workspace',
            'connectors/connector-reference/home-folder',
            'connectors/connector-reference/internal-resources',
            'connectors/connector-reference/internal-workflow',
            'connectors/connector-reference/json',
            'connectors/connector-reference/ldap',
            'connectors/connector-reference/ldif',
            'connectors/connector-reference/microsoft-entra-id',
            'connectors/connector-reference/microsoft-exchange',
            'connectors/connector-reference/odata',
            'connectors/connector-reference/okta',
            'connectors/connector-reference/openldap',
            'connectors/connector-reference/powershell-prov',
            'connectors/connector-reference/powershell-sync',
            'connectors/connector-reference/racf',
            'connectors/connector-reference/robot-framework',
            'connectors/connector-reference/sap-erp6',
            'connectors/connector-reference/sap-netweaver',
            'connectors/connector-reference/scim',
            'connectors/connector-reference/servicenow-entity',
            'connectors/connector-reference/servicenow-ticket',
            'connectors/connector-reference/shared-folder',
            'connectors/connector-reference/sharepoint',
            'connectors/connector-reference/sql',
            'connectors/connector-reference/sql-server-entitlements',
            'connectors/connector-reference/top-secret',
            'connectors/connector-reference/workday',
          ],
        },
        {
          type: 'category',
          label: 'Connector Packages',
          collapsed: true,
          items: [
            'connectors/packages/index',
            'connectors/packages/active-directory',
            'connectors/packages/apache-directory',
            'connectors/packages/azure',
            'connectors/packages/azure-active-directory',
            'connectors/packages/csv',
            'connectors/packages/cyberark',
            'connectors/packages/easyvista',
            'connectors/packages/easyvista-ticket',
            'connectors/packages/excel',
            'connectors/packages/generic-ldap',
            'connectors/packages/generic-scim',
            'connectors/packages/generic-sql',
            'connectors/packages/google-workspace',
            'connectors/packages/home-folders',
            'connectors/packages/identitymanager-database',
            'connectors/packages/json',
            'connectors/packages/ldif',
            'connectors/packages/manual-ticket',
            'connectors/packages/manual-ticket-cud',
            'connectors/packages/microsoft-exchange',
            'connectors/packages/mysql',
            'connectors/packages/odata',
            'connectors/packages/odbc',
            'connectors/packages/open-ldap',
            'connectors/packages/oracle-database',
            'connectors/packages/oracle-ldap',
            'connectors/packages/postgresql',
            'connectors/packages/powershell-prov',
            'connectors/packages/powershell-sync',
            'connectors/packages/racf',
            'connectors/packages/red-hat-directory',
            'connectors/packages/robot-framework',
            'connectors/packages/salesforce',
            'connectors/packages/sap-ase',
            'connectors/packages/sap-erp6',
            'connectors/packages/sap-hana',
            'connectors/packages/servicenow',
            'connectors/packages/servicenow-ticket',
            'connectors/packages/shared-folders',
            'connectors/packages/sharepoint',
            'connectors/packages/slack',
            'connectors/packages/sql-server',
            'connectors/packages/sql-server-entitlements',
            'connectors/packages/tss',
            'connectors/packages/unplugged',
            'connectors/packages/workday',
            'connectors/packages/workflow',
          ],
        },
        {
          type: 'category',
          label: 'How-to Guides',
          collapsed: true,
          items: [
            'connectors/how-to/index',
            'connectors/how-to/azure-ad-registration',
            'connectors/how-to/ticket-templates',
            {
              type: 'category',
              label: 'Create Connectors',
              collapsed: true,
              items: ['connectors/how-to/create-connectors/index', 'connectors/how-to/create-connectors/azure-ad'],
            },
            {
              type: 'category',
              label: 'Demo Apps',
              collapsed: true,
              items: ['connectors/how-to/demo-apps/hr', 'connectors/how-to/demo-apps/banking'],
            },
            {
              type: 'category',
              label: 'Exports',
              collapsed: true,
              items: ['connectors/how-to/exports/scim-cyberark', 'connectors/how-to/exports/scim-salesforce', 'connectors/how-to/exports/sharepoint'],
            },
            {
              type: 'category',
              label: 'Incremental Sync Setup',
              collapsed: true,
              items: ['connectors/how-to/incremental-sync-setup/index', 'connectors/how-to/incremental-sync-setup/azure-ad'],
            },
            {
              type: 'category',
              label: 'Scripting',
              collapsed: true,
              items: [
                'connectors/how-to/scripting/powershell-sync',
                'connectors/how-to/scripting/powershell-fulfill',
                'connectors/how-to/scripting/robotframework-fulfill',
                'connectors/how-to/scripting/robotframework-gui',
                'connectors/how-to/scripting/robotframework-web',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Synchronization',
      collapsed: true,
      items: ['synchronization/index', 'synchronization/synchronization-thresholds', 'synchronization/upward-data-sync'],
    },
    {
      type: 'category',
      label: 'Provisioning',
      collapsed: true,
      items: ['provisioning/index', 'provisioning/arguments-expression', 'provisioning/provisioning-thresholds'],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Tasks & Jobs',
          collapsed: true,
          items: [
            'automation/tasks-and-jobs/index',
            'automation/tasks-and-jobs/tasks',
            'automation/tasks-and-jobs/jobs',
            'automation/tasks-and-jobs/configure-jobs',
            'automation/tasks-and-jobs/configure-incremental-jobs',
            'automation/tasks-and-jobs/build-efficient-jobs',
            'automation/tasks-and-jobs/job-daily',
            'automation/tasks-and-jobs/job-fast',
            'automation/tasks-and-jobs/fulfill-ldap',
            'automation/tasks-and-jobs/troubleshoot-connector-jobs',
          ],
        },
        {
          type: 'category',
          label: 'Executables',
          collapsed: true,
          items: [
            'automation/executables/index',
            'automation/executables/agent',
            'automation/executables/server',
            'automation/executables/login',
            'automation/executables/anonymize',
            'automation/executables/check-expressions-consistency',
            'automation/executables/compute-correlation-keys',
            'automation/executables/configuration-transform',
            'automation/executables/create-database-views',
            'automation/executables/csv-transform',
            'automation/executables/decrypt-file',
            'automation/executables/deploy-configuration',
            'automation/executables/easyvista-ticket-update',
            'automation/executables/encrypt-file',
            'automation/executables/export-bacpac',
            'automation/executables/export-configuration',
            'automation/executables/export-csv',
            'automation/executables/export-easyvista',
            'automation/executables/export-excel',
            'automation/executables/export-scim',
            'automation/executables/fill-banking-database',
            'automation/executables/fulfill-easyvista',
            'automation/executables/fulfill-scim',
            'automation/executables/fulfill-to-easyvista-ticket',
            'automation/executables/generate-configuration',
            'automation/executables/get-job-steps',
            'automation/executables/invoke-job',
            'automation/executables/invoke-server-job',
            'automation/executables/manage-configuration-indexes',
            'automation/executables/manage-history',
            'automation/executables/new-openid-secret',
            'automation/executables/password-generator',
            'automation/executables/prepare-synchronization',
            'automation/executables/protect-certificate-password',
            'automation/executables/protect-x509-json-file',
            'automation/executables/protect-x509-json-value',
            'automation/executables/refresh-schema',
            'automation/executables/send-password-notification',
            'automation/executables/update-entity-property-expressions',
            'automation/executables/upgrade-configuration-version',
            'automation/executables/upgrade-database-version',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Notifications',
      collapsed: true,
      items: [
        'notifications/index',
        'notifications/custom-notifications',
        'notifications/customize-native-notifications',
        'notifications/set-language',
        {
          type: 'category',
          label: 'Native Notifications',
          collapsed: true,
          items: [
            'notifications/native-notifications/index',
            'notifications/native-notifications/access-certification',
            'notifications/native-notifications/errored-jobs',
            'notifications/native-notifications/manual-provisioning',
            'notifications/native-notifications/password-reset',
            'notifications/native-notifications/provisioning-review',
            'notifications/native-notifications/role-review',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      collapsed: true,
      items: [
        'governance/index',
        'governance/access-certification',
        'governance/risks',
        'governance/review-prolonged-entitlements',
        {
          type: 'category',
          label: 'Reporting',
          collapsed: true,
          items: ['governance/reporting/index', 'governance/reporting/connect-powerbi', 'governance/reporting/analyze-powerbi'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Toolkit',
      collapsed: true,
      items: [
        'toolkit/index',
        'toolkit/file-hierarchy',
        'toolkit/export-configuration',
        'toolkit/deploy-configuration',
        'toolkit/adjust-scaffoldings',
        'toolkit/bindings',
        'toolkit/languages',
        'toolkit/parameter-names',
        'toolkit/reserved-identifiers',
        'toolkit/recommendations',
        {
          type: 'category',
          label: 'Expressions',
          collapsed: true,
          items: ['toolkit/expressions/index', 'toolkit/expressions/predefined-functions', 'toolkit/expressions/csharp-utilities'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsed: true,
      items: [
        'configuration/index',
        {
          type: 'category',
          label: 'Network',
          collapsed: true,
          items: [
            'configuration/network/index',
            'configuration/network/proxy',
            'configuration/network/password-management',
            'configuration/network/okta-integration',
            {
              type: 'category',
              label: 'Server Settings',
              collapsed: true,
              items: [
                'configuration/network/server-settings/index',
                'configuration/network/server-settings/database-connection',
                'configuration/network/server-settings/general-purpose',
                'configuration/network/server-settings/end-user-authentication',
                'configuration/network/server-settings/rsa-encryption',
              ],
            },
            {
              type: 'category',
              label: 'Agent Settings',
              collapsed: true,
              items: [
                'configuration/network/agent-settings/index',
                'configuration/network/agent-settings/appsettings',
                'configuration/network/agent-settings/azure-key-vault',
                'configuration/network/agent-settings/cyberark-credential-providers',
                'configuration/network/agent-settings/rsa-encryption',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Technical Files',
          collapsed: true,
          items: ['configuration/technical-files/index', 'configuration/technical-files/appsettings-connection'],
        },
        {
          type: 'category',
          label: 'XML Configuration',
          collapsed: true,
          items: [
            'configuration/xml-configuration/index',
            'configuration/xml-configuration/access-control',
            'configuration/xml-configuration/access-certification',
            'configuration/xml-configuration/business-intelligence',
            'configuration/xml-configuration/scaffoldings',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        'api-reference/index',
        'api-reference/authentication',
        'api-reference/pagination',
        'api-reference/squery',
        'api-reference/postman-requests',
      ],
    },
    {
      type: 'category',
      label: 'Monitoring',
      collapsed: true,
      items: ['monitoring/index', 'monitoring/monitoring-reference', 'monitoring/qradar-setup'],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: true,
      items: ['modules/index'],
    },
  ],
};

export default sidebars;
