module.exports = {
  identityManagerSaaS: [
    'identitymanager/saas/index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'identitymanager/saas/getting-started/index',
        'identitymanager/saas/getting-started/quick-start',
        'identitymanager/saas/getting-started/requirements',
      ],
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        'identitymanager/saas/installation/index',
        'identitymanager/saas/installation/overview',
        {
          type: 'category',
          label: 'Production Setup',
          items: [
            'identitymanager/saas/installation/production-setup/index',
            'identitymanager/saas/installation/production-setup/server',
            'identitymanager/saas/installation/production-setup/agent',
            'identitymanager/saas/installation/production-setup/database',
            'identitymanager/saas/installation/production-setup/email-server',
            'identitymanager/saas/installation/production-setup/working-directory',
          ],
        },
        'identitymanager/saas/installation/reverse-proxy',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'identitymanager/saas/architecture/index',
        'identitymanager/saas/architecture/on-premise',
        'identitymanager/saas/architecture/saas',
        'identitymanager/saas/architecture/secure-agent-communication',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'identitymanager/saas/configuration/index',
        {
          type: 'category',
          label: 'Network',
          items: [
            'identitymanager/saas/configuration/network/index',
            {
              type: 'category',
              label: 'Server Settings',
              items: [
                'identitymanager/saas/configuration/network/server-settings/index',
                'identitymanager/saas/configuration/network/server-settings/database-connection',
                'identitymanager/saas/configuration/network/server-settings/general-purpose',
                'identitymanager/saas/configuration/network/server-settings/end-user-authentication',
                'identitymanager/saas/configuration/network/server-settings/rsa-encryption',
              ],
            },
            {
              type: 'category',
              label: 'Agent Settings',
              items: [
                'identitymanager/saas/configuration/network/agent-settings/index',
                'identitymanager/saas/configuration/network/agent-settings/appsettings',
                'identitymanager/saas/configuration/network/agent-settings/azure-key-vault',
                'identitymanager/saas/configuration/network/agent-settings/cyberark-credential-providers',
                'identitymanager/saas/configuration/network/agent-settings/rsa-encryption',
              ],
            },
            'identitymanager/saas/configuration/network/proxy',
            'identitymanager/saas/configuration/network/password-management',
            'identitymanager/saas/configuration/network/okta-integration',
          ],
        },
        {
          type: 'category',
          label: 'Technical Files',
          items: [
            'identitymanager/saas/configuration/technical-files/index',
            'identitymanager/saas/configuration/technical-files/appsettings-connection',
          ],
        },
        {
          type: 'category',
          label: 'XML Configuration',
          items: [
            'identitymanager/saas/configuration/xml-configuration/index',
            'identitymanager/saas/configuration/xml-configuration/access-certification',
            'identitymanager/saas/configuration/xml-configuration/access-control',
            'identitymanager/saas/configuration/xml-configuration/business-intelligence',
            'identitymanager/saas/configuration/xml-configuration/scaffoldings',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Connectors',
      items: [
        'identitymanager/saas/connectors/index',
        {
          type: 'category',
          label: 'Configuration',
          items: [
            'identitymanager/saas/connectors/configuration/index',
            'identitymanager/saas/connectors/configuration/connections',
            'identitymanager/saas/connectors/configuration/credential-protection',
            'identitymanager/saas/connectors/configuration/secured-options',
            'identitymanager/saas/connectors/configuration/entity-property-mapping',
          ],
        },
        {
          type: 'category',
          label: 'How To',
          items: [
            'identitymanager/saas/connectors/how-to/index',
            {
              type: 'category',
              label: 'Create Connectors',
              items: [
                'identitymanager/saas/connectors/how-to/create-connectors/index',
                'identitymanager/saas/connectors/how-to/create-connectors/azure-ad',
              ],
            },
            'identitymanager/saas/connectors/how-to/azure-ad-registration',
            {
              type: 'category',
              label: 'Incremental Sync Setup',
              items: [
                'identitymanager/saas/connectors/how-to/incremental-sync-setup/index',
                'identitymanager/saas/connectors/how-to/incremental-sync-setup/azure-ad',
              ],
            },
            {
              type: 'category',
              label: 'Scripting',
              items: [
                'identitymanager/saas/connectors/how-to/scripting/index',
                'identitymanager/saas/connectors/how-to/scripting/powershell-sync',
                'identitymanager/saas/connectors/how-to/scripting/powershell-fulfill',
                'identitymanager/saas/connectors/how-to/scripting/robotframework-gui',
                'identitymanager/saas/connectors/how-to/scripting/robotframework-web',
                'identitymanager/saas/connectors/how-to/scripting/robotframework-fulfill',
              ],
            },
            {
              type: 'category',
              label: 'Demo Apps',
              items: [
                'identitymanager/saas/connectors/how-to/demo-apps/index',
                'identitymanager/saas/connectors/how-to/demo-apps/banking',
                'identitymanager/saas/connectors/how-to/demo-apps/hr',
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'identitymanager/saas/connectors/how-to/exports/index',
                'identitymanager/saas/connectors/how-to/exports/scim-cyberark',
                'identitymanager/saas/connectors/how-to/exports/scim-salesforce',
                'identitymanager/saas/connectors/how-to/exports/sharepoint',
              ],
            },
            'identitymanager/saas/connectors/how-to/ticket-templates',
          ],
        },
        {
          type: 'category',
          label: 'Connector Reference',
          collapsed: true,
          items: [
            'identitymanager/saas/connectors/connector-reference/index',
            'identitymanager/saas/connectors/connector-reference/active-directory',
            'identitymanager/saas/connectors/connector-reference/azure',
            'identitymanager/saas/connectors/connector-reference/csv',
            'identitymanager/saas/connectors/connector-reference/easyvista',
            'identitymanager/saas/connectors/connector-reference/easyvista-ticket',
            'identitymanager/saas/connectors/connector-reference/excel',
            'identitymanager/saas/connectors/connector-reference/google-workspace',
            'identitymanager/saas/connectors/connector-reference/home-folder',
            'identitymanager/saas/connectors/connector-reference/internal-resources',
            'identitymanager/saas/connectors/connector-reference/internal-workflow',
            'identitymanager/saas/connectors/connector-reference/json',
            'identitymanager/saas/connectors/connector-reference/ldap',
            'identitymanager/saas/connectors/connector-reference/ldif',
            'identitymanager/saas/connectors/connector-reference/microsoft-entra-id',
            'identitymanager/saas/connectors/connector-reference/microsoft-exchange',
            'identitymanager/saas/connectors/connector-reference/odata',
            'identitymanager/saas/connectors/connector-reference/okta',
            'identitymanager/saas/connectors/connector-reference/openldap',
            'identitymanager/saas/connectors/connector-reference/powershell-prov',
            'identitymanager/saas/connectors/connector-reference/powershell-sync',
            'identitymanager/saas/connectors/connector-reference/racf',
            'identitymanager/saas/connectors/connector-reference/robot-framework',
            'identitymanager/saas/connectors/connector-reference/sap-erp6',
            'identitymanager/saas/connectors/connector-reference/sap-netweaver',
            'identitymanager/saas/connectors/connector-reference/scim',
            'identitymanager/saas/connectors/connector-reference/servicenow-entity',
            'identitymanager/saas/connectors/connector-reference/servicenow-ticket',
            'identitymanager/saas/connectors/connector-reference/shared-folder',
            'identitymanager/saas/connectors/connector-reference/sharepoint',
            'identitymanager/saas/connectors/connector-reference/sql',
            'identitymanager/saas/connectors/connector-reference/sql-server-entitlements',
            'identitymanager/saas/connectors/connector-reference/top-secret',
            'identitymanager/saas/connectors/connector-reference/workday',
          ],
        },
        {
          type: 'category',
          label: 'Packages',
          collapsed: true,
          items: [
            'identitymanager/saas/connectors/packages/index',
            'identitymanager/saas/connectors/packages/active-directory',
            'identitymanager/saas/connectors/packages/apache-directory',
            'identitymanager/saas/connectors/packages/azure',
            'identitymanager/saas/connectors/packages/azure-active-directory',
            'identitymanager/saas/connectors/packages/csv',
            'identitymanager/saas/connectors/packages/cyberark',
            'identitymanager/saas/connectors/packages/easyvista',
            'identitymanager/saas/connectors/packages/easyvista-ticket',
            'identitymanager/saas/connectors/packages/excel',
            'identitymanager/saas/connectors/packages/generic-ldap',
            'identitymanager/saas/connectors/packages/generic-scim',
            'identitymanager/saas/connectors/packages/generic-sql',
            'identitymanager/saas/connectors/packages/google-workspace',
            'identitymanager/saas/connectors/packages/home-folders',
            'identitymanager/saas/connectors/packages/identitymanager-database',
            'identitymanager/saas/connectors/packages/json',
            'identitymanager/saas/connectors/packages/ldif',
            'identitymanager/saas/connectors/packages/manual-ticket',
            'identitymanager/saas/connectors/packages/manual-ticket-cud',
            'identitymanager/saas/connectors/packages/microsoft-exchange',
            'identitymanager/saas/connectors/packages/mysql',
            'identitymanager/saas/connectors/packages/odata',
            'identitymanager/saas/connectors/packages/odbc',
            'identitymanager/saas/connectors/packages/open-ldap',
            'identitymanager/saas/connectors/packages/oracle-database',
            'identitymanager/saas/connectors/packages/oracle-ldap',
            'identitymanager/saas/connectors/packages/postgresql',
            'identitymanager/saas/connectors/packages/powershell-prov',
            'identitymanager/saas/connectors/packages/powershell-sync',
            'identitymanager/saas/connectors/packages/racf',
            'identitymanager/saas/connectors/packages/red-hat-directory',
            'identitymanager/saas/connectors/packages/robot-framework',
            'identitymanager/saas/connectors/packages/salesforce',
            'identitymanager/saas/connectors/packages/sap-ase',
            'identitymanager/saas/connectors/packages/sap-erp6',
            'identitymanager/saas/connectors/packages/sap-hana',
            'identitymanager/saas/connectors/packages/servicenow',
            'identitymanager/saas/connectors/packages/servicenow-ticket',
            'identitymanager/saas/connectors/packages/shared-folders',
            'identitymanager/saas/connectors/packages/sharepoint',
            'identitymanager/saas/connectors/packages/slack',
            'identitymanager/saas/connectors/packages/sql-server',
            'identitymanager/saas/connectors/packages/sql-server-entitlements',
            'identitymanager/saas/connectors/packages/tss',
            'identitymanager/saas/connectors/packages/unplugged',
            'identitymanager/saas/connectors/packages/workday',
            'identitymanager/saas/connectors/packages/workflow',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Identity Management',
      items: [
        'identitymanager/saas/identity-management/index',
        'identitymanager/saas/identity-management/identity-repository',
        {
          type: 'category',
          label: 'Joiners, Movers & Leavers',
          items: [
            'identitymanager/saas/identity-management/joiners-movers-leavers/index',
            'identitymanager/saas/identity-management/joiners-movers-leavers/onboarding-offboarding',
            'identitymanager/saas/identity-management/joiners-movers-leavers/position-changes',
          ],
        },
        'identitymanager/saas/identity-management/entity-model',
      ],
    },
    {
      type: 'category',
      label: 'Role Management',
      items: [
        'identitymanager/saas/role-management/index',
        'identitymanager/saas/role-management/role-model',
        'identitymanager/saas/role-management/role-model-rules',
        'identitymanager/saas/role-management/role-mining',
        {
          type: 'category',
          label: 'Role Assignment',
          items: [
            'identitymanager/saas/role-management/role-assignment/index',
            'identitymanager/saas/role-management/role-assignment/assignment-dates',
            'identitymanager/saas/role-management/role-assignment/entitlement-assignments',
            'identitymanager/saas/role-management/role-assignment/conforming-assignments',
            'identitymanager/saas/role-management/role-assignment/evaluate-policy',
            'identitymanager/saas/role-management/role-assignment/existing-assignments',
            'identitymanager/saas/role-management/role-assignment/generate-contexts',
            'identitymanager/saas/role-management/role-assignment/indirect-permissions',
            'identitymanager/saas/role-management/role-assignment/nonconforming-detection',
            'identitymanager/saas/role-management/role-assignment/configure-indirect-permissions',
            'identitymanager/saas/role-management/role-assignment/infer-single-roles',
            'identitymanager/saas/role-management/role-assignment/restrict-assignments',
          ],
        },
        'identitymanager/saas/role-management/simulation',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        'identitymanager/saas/governance/index',
        'identitymanager/saas/governance/access-certification',
        'identitymanager/saas/governance/risks',
        'identitymanager/saas/governance/review-prolonged-entitlements',
        {
          type: 'category',
          label: 'Reporting',
          items: [
            'identitymanager/saas/governance/reporting/index',
            'identitymanager/saas/governance/reporting/connect-powerbi',
            'identitymanager/saas/governance/reporting/analyze-powerbi',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Provisioning',
      items: [
        'identitymanager/saas/provisioning/index',
        'identitymanager/saas/provisioning/provisioning-thresholds',
        'identitymanager/saas/provisioning/arguments-expression',
      ],
    },
    {
      type: 'category',
      label: 'Synchronization',
      items: [
        'identitymanager/saas/synchronization/index',
        'identitymanager/saas/synchronization/synchronization-thresholds',
        'identitymanager/saas/synchronization/upward-data-sync',
      ],
    },
    {
      type: 'category',
      label: 'Automation',
      items: [
        'identitymanager/saas/automation/index',
        {
          type: 'category',
          label: 'Tasks and Jobs',
          items: [
            'identitymanager/saas/automation/tasks-and-jobs/index',
            'identitymanager/saas/automation/tasks-and-jobs/tasks',
            'identitymanager/saas/automation/tasks-and-jobs/jobs',
            'identitymanager/saas/automation/tasks-and-jobs/configure-jobs',
            'identitymanager/saas/automation/tasks-and-jobs/build-efficient-jobs',
            'identitymanager/saas/automation/tasks-and-jobs/configure-incremental-jobs',
            'identitymanager/saas/automation/tasks-and-jobs/troubleshoot-connector-jobs',
            'identitymanager/saas/automation/tasks-and-jobs/fulfill-ldap',
            'identitymanager/saas/automation/tasks-and-jobs/job-daily',
            'identitymanager/saas/automation/tasks-and-jobs/job-fast',
          ],
        },
        {
          type: 'category',
          label: 'Executables',
          collapsed: true,
          items: [
            'identitymanager/saas/automation/executables/index',
            'identitymanager/saas/automation/executables/agent',
            'identitymanager/saas/automation/executables/server',
            'identitymanager/saas/automation/executables/anonymize',
            'identitymanager/saas/automation/executables/check-expressions-consistency',
            'identitymanager/saas/automation/executables/compute-correlation-keys',
            'identitymanager/saas/automation/executables/configuration-transform',
            'identitymanager/saas/automation/executables/create-database-views',
            'identitymanager/saas/automation/executables/csv-transform',
            'identitymanager/saas/automation/executables/decrypt-file',
            'identitymanager/saas/automation/executables/deploy-configuration',
            'identitymanager/saas/automation/executables/easyvista-ticket-update',
            'identitymanager/saas/automation/executables/encrypt-file',
            'identitymanager/saas/automation/executables/export-bacpac',
            'identitymanager/saas/automation/executables/export-configuration',
            'identitymanager/saas/automation/executables/export-csv',
            'identitymanager/saas/automation/executables/export-easyvista',
            'identitymanager/saas/automation/executables/export-excel',
            'identitymanager/saas/automation/executables/export-scim',
            'identitymanager/saas/automation/executables/fill-banking-database',
            'identitymanager/saas/automation/executables/fulfill-easyvista',
            'identitymanager/saas/automation/executables/fulfill-scim',
            'identitymanager/saas/automation/executables/fulfill-to-easyvista-ticket',
            'identitymanager/saas/automation/executables/generate-configuration',
            'identitymanager/saas/automation/executables/get-job-steps',
            'identitymanager/saas/automation/executables/invoke-job',
            'identitymanager/saas/automation/executables/invoke-server-job',
            'identitymanager/saas/automation/executables/login',
            'identitymanager/saas/automation/executables/manage-configuration-indexes',
            'identitymanager/saas/automation/executables/manage-history',
            'identitymanager/saas/automation/executables/new-openid-secret',
            'identitymanager/saas/automation/executables/password-generator',
            'identitymanager/saas/automation/executables/prepare-synchronization',
            'identitymanager/saas/automation/executables/protect-certificate-password',
            'identitymanager/saas/automation/executables/protect-x509-json-file',
            'identitymanager/saas/automation/executables/protect-x509-json-value',
            'identitymanager/saas/automation/executables/refresh-schema',
            'identitymanager/saas/automation/executables/send-password-notification',
            'identitymanager/saas/automation/executables/update-entity-property-expressions',
            'identitymanager/saas/automation/executables/upgrade-configuration-version',
            'identitymanager/saas/automation/executables/upgrade-database-version',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Access Control',
      items: [
        'identitymanager/saas/access-control/index',
        {
          type: 'category',
          label: 'Profiles and Permissions',
          items: [
            'identitymanager/saas/access-control/profiles-and-permissions/index',
            'identitymanager/saas/access-control/profiles-and-permissions/permissions',
            'identitymanager/saas/access-control/profiles-and-permissions/create-assign-profiles',
            'identitymanager/saas/access-control/profiles-and-permissions/rights-restriction',
          ],
        },
        'identitymanager/saas/access-control/resources',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'identitymanager/saas/api-reference/index',
        'identitymanager/saas/api-reference/authentication',
        'identitymanager/saas/api-reference/pagination',
        'identitymanager/saas/api-reference/squery',
        'identitymanager/saas/api-reference/postman-requests',
      ],
    },
    {
      type: 'category',
      label: 'Monitoring',
      items: [
        'identitymanager/saas/monitoring/index',
        'identitymanager/saas/monitoring/monitoring-reference',
        'identitymanager/saas/monitoring/qradar-setup',
      ],
    },
    {
      type: 'category',
      label: 'Notifications',
      items: [
        'identitymanager/saas/notifications/index',
        {
          type: 'category',
          label: 'Native Notifications',
          items: [
            'identitymanager/saas/notifications/native-notifications/index',
            'identitymanager/saas/notifications/native-notifications/access-certification',
            'identitymanager/saas/notifications/native-notifications/errored-jobs',
            'identitymanager/saas/notifications/native-notifications/manual-provisioning',
            'identitymanager/saas/notifications/native-notifications/password-reset',
            'identitymanager/saas/notifications/native-notifications/provisioning-review',
            'identitymanager/saas/notifications/native-notifications/role-review',
          ],
        },
        'identitymanager/saas/notifications/custom-notifications',
        'identitymanager/saas/notifications/customize-native-notifications',
        'identitymanager/saas/notifications/set-language',
      ],
    },
    {
      type: 'category',
      label: 'Toolkit',
      items: [
        'identitymanager/saas/toolkit/index',
        'identitymanager/saas/toolkit/file-hierarchy',
        'identitymanager/saas/toolkit/bindings',
        {
          type: 'category',
          label: 'Expressions',
          items: [
            'identitymanager/saas/toolkit/expressions/index',
            'identitymanager/saas/toolkit/expressions/csharp-utilities',
            'identitymanager/saas/toolkit/expressions/predefined-functions',
          ],
        },
        'identitymanager/saas/toolkit/languages',
        'identitymanager/saas/toolkit/parameter-names',
        'identitymanager/saas/toolkit/recommendations',
        'identitymanager/saas/toolkit/reserved-identifiers',
        'identitymanager/saas/toolkit/deploy-configuration',
        'identitymanager/saas/toolkit/export-configuration',
        'identitymanager/saas/toolkit/adjust-scaffoldings',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: ['identitymanager/saas/modules/index'],
    },
  ],
};
