// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const pingcastleSidebar = {
  sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default pingcastleSidebar;
