// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  privilegeSecure41Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
}

export default sidebars
